# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from puppy_control2/ServoControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ServoControl(genpy.Message):
  _md5sum = "326b3455b95de3ececfaa8d7b1eb8c40"
  _type = "puppy_control2/ServoControl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 frontleftx
float32 frontleftz

float32 frontrightx
float32 frontrightz

float32 backleftx
float32 backleftz

float32 backrightx
float32 backrightz
"""
  __slots__ = ['frontleftx','frontleftz','frontrightx','frontrightz','backleftx','backleftz','backrightx','backrightz']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frontleftx,frontleftz,frontrightx,frontrightz,backleftx,backleftz,backrightx,backrightz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ServoControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.frontleftx is None:
        self.frontleftx = 0.
      if self.frontleftz is None:
        self.frontleftz = 0.
      if self.frontrightx is None:
        self.frontrightx = 0.
      if self.frontrightz is None:
        self.frontrightz = 0.
      if self.backleftx is None:
        self.backleftx = 0.
      if self.backleftz is None:
        self.backleftz = 0.
      if self.backrightx is None:
        self.backrightx = 0.
      if self.backrightz is None:
        self.backrightz = 0.
    else:
      self.frontleftx = 0.
      self.frontleftz = 0.
      self.frontrightx = 0.
      self.frontrightz = 0.
      self.backleftx = 0.
      self.backleftz = 0.
      self.backrightx = 0.
      self.backrightz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.frontleftx, _x.frontleftz, _x.frontrightx, _x.frontrightz, _x.backleftx, _x.backleftz, _x.backrightx, _x.backrightz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.frontleftx, _x.frontleftz, _x.frontrightx, _x.frontrightz, _x.backleftx, _x.backleftz, _x.backrightx, _x.backrightz,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.frontleftx, _x.frontleftz, _x.frontrightx, _x.frontrightz, _x.backleftx, _x.backleftz, _x.backrightx, _x.backrightz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.frontleftx, _x.frontleftz, _x.frontrightx, _x.frontrightz, _x.backleftx, _x.backleftz, _x.backrightx, _x.backrightz,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
